[tool.poetry]
name = "walk-man"
version = "0.1.0"
description = ""
authors = ["Robert Schöne"]
license = "GPL"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pygame = "^2.6.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
